[package]
name = "toy-c-compiler"
version = "0.1.0"
authors = ["y_fukuda <colors92window@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
